#!/usr/bin/env php
<?php

include __DIR__."/../vendor/autoload.php";

use App\EntityManagerProvider;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;

$entityManager = EntityManagerProvider::getEntityManager();

ConsoleRunner::run(
    new SingleManagerProvider($entityManager)
);